        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 09 04:17:26 2018
        MODULE ANALYTIC_SOLUTIONS__genmod
          INTERFACE 
            SUBROUTINE ANALYTIC_SOLUTIONS(N,VELO)
              INTEGER(KIND=4) :: N
              REAL(KIND=4) :: VELO
            END SUBROUTINE ANALYTIC_SOLUTIONS
          END INTERFACE 
        END MODULE ANALYTIC_SOLUTIONS__genmod
