        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 09 04:17:26 2018
        MODULE ANALYTIC_SOL__genmod
          INTERFACE 
            SUBROUTINE ANALYTIC_SOL(N,VELO)
              INTEGER(KIND=4) :: N
              REAL(KIND=4) :: VELO
            END SUBROUTINE ANALYTIC_SOL
          END INTERFACE 
        END MODULE ANALYTIC_SOL__genmod
