        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 09 04:17:26 2018
        MODULE CENTER_FORMAT__genmod
          INTERFACE 
            SUBROUTINE CENTER_FORMAT(N,VELO)
              INTEGER(KIND=4) :: N
              REAL(KIND=4) :: VELO
            END SUBROUTINE CENTER_FORMAT
          END INTERFACE 
        END MODULE CENTER_FORMAT__genmod
